web/urls.py
# -*- coding: utf-8 -*- 
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()


urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'web.views.home_view', name='home'),
    url(r'^rezervace/$', 'web.views.rezervace_view', name='rezervace'),
    url(r'^kontakt/$', 'web.views.kontakt_view', name='web-kontakt'),
    url(r'^o-nas/$', 'web.views.onas_view', name='web-onas'),
    url(r'^vouchery/$', 'web.views.vouchery_view', name='web-vouchery'),
    url(r'^kredit/$', 'web.views.kredit_view', name='web-kredit'),
    url(r'^cancel_reservation/$', 'web.views.cancel_reservation', name='web-cancel-reservation'),
    url(r'^ajax/get_sportoviste/$', 'web.views.ajax_get_sportoviste', name='ajax-get-sportoviste'),
    url(r'^ajax/get_calendar/$', 'web.views.ajax_get_table_calendar', name='ajax-get-table-calendar'),
    url(r'^ajax/make_reservation/$', 'web.views.ajax_make_reservation', name='ajax-make-reservation'),
    url(r'^ajax/pay/$', 'web.views.ajax_pay', name='ajax-pay'),
    url(r'^ajax/delete_reservation/$', 'web.views.ajax_delete_rezervace', name='ajax-delete-rezervace'),
)

core/models.py
# -*- coding: utf-8 -*-
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models
from .managers import UserManager


class User(AbstractBaseUser, PermissionsMixin):
    jmeno = models.CharField(max_length=40, null=True)
    prijmeni = models.CharField(max_length=40, null=True)

    email = models.EmailField(db_index=True, unique=True, verbose_name=u"Email")
    RC = models.CharField(max_length=12)
    telefon = models.CharField(max_length=25)

    konto = models.FloatField(default=0, verbose_name=u"Konto")

    is_active = models.BooleanField(default=False, verbose_name=u"Aktivován")
    is_manager = models.BooleanField(default=False, verbose_name=u"Zaměstnanec")

    def get_full_name(self):
        return "{0} {1}".format(self.jmeno, self.prijmeni) if self.jmeno and self.prijmeni else self.email

    def get_short_name(self):
        return self.get_full_name()

    def activate(self):
        """ Activates user to using account on Futruy
        """
        self.is_active = True
        self.save()

    @property
    def is_staff(self):
        return self.is_manager or self.is_superuser

    USERNAME_FIELD = 'email'

    objects = UserManager()

    class Meta:
        db_table = 'users'

    def create_user(self, email, password, firstName=None, lastName=None, is_superuser=False, is_active=False, is_manager=False):

        self.email = email
        self.set_password(password)
        self.is_active = is_active
        self.is_superuser = is_superuser
        self.is_manager = is_manager
        self.first_name = firstName
        self.last_name = lastName
        self.set_activation_string()

        return self.save()

    def add_money(self, money_amount):
        """ Prida penize na konto uzivatele
        """
        self.konto += money_amount
        self.save()


class Voucher(models.Model):
    """
    """
    id = models.IntegerField(primary_key=True, verbose_name=u"ID voucheru")
    castka = models.FloatField(verbose_name=u"Částka")
    platny_od = models.DateTimeField(verbose_name=u"Platný od", help_text=u"ve tvaru yyyy-mm-dd")
    platny_do = models.DateTimeField(verbose_name=u"Platný do", help_text=u"ve tvaru yyyy-mm-dd")
    vydal_uzivatel = models.ForeignKey(User, verbose_name=u"Vydal uživatel")
    uplatnil_uzivatel = models.ForeignKey(User, null=True, blank=True, verbose_name=u"Uplatnil uživatel",
                                          related_name="uplatnil_uzivatel_set")

    def __unicode__(self):
        return "Voucher {0}".format(self.pk)


class SportovniCentrum(models.Model):
    """

    """
    nazev = models.CharField(max_length=50, verbose_name=u"Název")
    ulice = models.CharField(max_length=50, verbose_name=u"Ulice", help_text=u"Včetně čísla popisného a orientačního")
    mesto = models.CharField(max_length=50, verbose_name=u"Město")
    psc = models.IntegerField(max_length=5)
    popis = models.TextField(null=True, blank=True, verbose_name=u"Popis")

    def __unicode__(self):
        return u"{} {}".format(self.nazev, self.mesto)

    def adresa(self):
        return u"{} {}".format(self.ulice, self.mesto)


class Sportoviste(models.Model):
    sportovni_centrum = models.ForeignKey(SportovniCentrum, verbose_name=u"Sportovní centrum")
    nazev = models.CharField(max_length=60, verbose_name=u"Název")
    interval_vypujcek = models.TimeField(verbose_name=u"Interval výpujček", help_text=u"Ve formátu hh:mm (např. 1:30)")
    zacatek_provozu = models.TimeField(verbose_name=u"Začátek provozu", help_text=u"Ve formátu hh:mm (např. 9:30)")
    konec_provozu = models.TimeField(verbose_name=u"Konec provozu", help_text=u"Ve formátu hh:mm (např. 19:30)")
    cena_interval = models.FloatField(verbose_name=u"Cena za interval", help_text=u"V Kč")
    popis = models.TextField(null=True, blank=True, verbose_name=u"Popis")

    def __unicode__(self):
        return self.nazev

    def serialize(self):
        return {
            'nazev': self.nazev,
            'interval_vypujcek_hodiny': self.interval_vypujcek.hour,
            'interval_vypujcek_minuty': self.interval_vypujcek.minute,
            'interval_vypujcek': self.interval_vypujcek.minute + self.interval_vypujcek.hour * 60,
            'zacatek_provozu_hodiny': self.zacatek_provozu.hour,
            'zacatek_provozu_minuty': self.zacatek_provozu.minute,
            'zacatek_provozu': self.zacatek_provozu.minute + self.zacatek_provozu.hour * 60,
            'konec_provozu_hodiny': self.konec_provozu.hour,
            'konec_provozu_minuty': self.konec_provozu.minute,
            'konec_provozu': self.konec_provozu.minute + self.konec_provozu.hour * 60,
            'popis': self.popis,
            'cena_interval': self.cena_interval,
            'id': self.id
        }

    def interval_vypujcek_minuty(self):
        return self.interval_vypujcek.minute + self.interval_vypujcek.hour * 60


class SportovisteMisto(models.Model):
    """ Pridana trida, neni v analyze. Urcuje misto sportoviste (napr. Kurt 1, Kurt 2,
    Bowlingova draha 1, Bowlingova draha 2... )
    """

    sportoviste = models.ForeignKey(Sportoviste, verbose_name=u"Sportoviště")
    nazev = models.CharField(max_length=60, verbose_name=u"Název")

    def __unicode__(self):
        return u"{0} - {1} - {2}".format(self.sportoviste.sportovni_centrum.nazev, self.sportoviste.nazev, self.nazev)

    def serialize(self, date=None):
        date1 = date.replace(hour=0, minute=0) if date else None
        date2 = date.replace(hour=23, minute=59) if date else None

        rezervace_list = self.rezervace_set.all().order_by('rezervace_od') if not date else self.rezervace_set.filter(rezervace_od__gte=date1, rezervace_do__lte=date2).order_by('rezervace_od')

        return {
            'id': self.id,
            'nazev': self.nazev,
            'rezervace': [rezervace.serialize() for rezervace in rezervace_list]

        }


class Rezervace(models.Model):

    STAV_CHOICES = (
        (0, 'Rezervováno'),
        (1, 'Provozuje'),
        (2, 'Zaplacano'),
        (3, 'Propadlo'),
    )

    misto = models.ForeignKey(SportovisteMisto, verbose_name=u"Místo")
    zakaznik = models.ForeignKey(User, verbose_name=u"Zákazník")
    cena = models.FloatField(verbose_name=u"Cena")
    rezervace_od = models.DateTimeField(verbose_name=u"Rezervace od")
    rezervace_do = models.DateTimeField(verbose_name=u"Rezervace do")
    stav = models.SmallIntegerField(choices=STAV_CHOICES)
    # je rezervace jiz zaplacena?
    zaplaceno = models.BooleanField(default=False)

    def __unicode__(self):
        return u"{0} - {1} - {2}".format(self.misto.sportoviste, self.misto.nazev, self.zakaznik.get_full_name())

    def print_user(self):
        return u"{0} - {1} - {2}".format(self.misto.sportoviste, self.misto, self.rezervace_od)

    def serialize(self):
        return {
            'id': self.id,
            'zakaznik_id': self.zakaznik_id,
            'zakaznik_jmeno': self.zakaznik.get_full_name(),
            'rezervace_od': self.rezervace_od.isoformat(),
            'rezervace_od_alt': self.rezervace_od.minute + self.rezervace_od.hour * 60 + 60,
            'rezervace_do': self.rezervace_do.isoformat(),
            'rezervace_do_alt': self.rezervace_do.minute + self.rezervace_do.hour * 60 + 60,
            'rezervace_datum': self.rezervace_od.strftime("%m/%d/%Y"),
            'cena': self.cena,
            'stav': self.stav,
            'zaplaceno': self.zaplaceno
        }

templates/web/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../docs-assets/ico/favicon.png">

    <title>Sportovní centrum</title>

    <!-- Bootstrap core CSS -->
    <link href="{{ STATIC_URL }}css/bootstrap.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}css/style.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}css/ui-lightness/jquery-ui-1.10.3.custom.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="navbar-fixed-top.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../docs-assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Sport centrum</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'rezervace' %}">Rezervace</a></li>
            <li><a href="{% url 'web-onas' %}">O nás</a></li>
            <li><a href="{% url 'web-kontakt' %}">Kontakt</a></li>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
              {% if not user.is_authenticated %}
            <li><a href="{% url 'accounts-login' %}">Přihlásit se</a></li>
              {% else %}
                  {% if user.is_staff %}
                      <li><a href="{% url 'admin-home' %}">Admin</a></li>
                   {% endif %}
            <li class="dropdown">
                <a href="" class="dropdown-toggle" data-toggle="dropdown">Můj účet <small>({{ user.konto }} Kč)</small><b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'web-vouchery' %}">Vouchery</a></li>
                    <li><a href="{% url 'web-kredit' %}">Dobití kreditu</a></li>
                    <li><a href="{% url 'rezervace' %}">Mé rezervace</a></li>
                    <hr>
                    <li><a href="{% url 'accounts-detail' %}">Nastavení</a></li>

                </ul>
            </li>
             <li><a href="{% url 'accounts-logout' %}">Odhlásit - <small>{{ user }}</small></a></li>
              {% endif %}

          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container" id="content">

     {% block content %}

     {% endblock %}

    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{{ STATIC_URL }}js/jquery-ui-1.10.3.custom.min.js"></script>

    <script src="{{ STATIC_URL }}js/bootstrap.min.js"></script>
    <script src="{{ STATIC_URL }}js/script.js"></script>
  </body>
</html>

templates/web/index.html
{% extends 'web/base.html' %}

{% block content %}
<div class="row-fluid">
    <div class="col-lg-12 col-md-12 col-sm-12">
        {% for sc in sportovni_centra %}
        <h2>{{ sc.nazev }}</h2>
        <p>{{ sc.popis }}</p>
            <strong>Sportoviště centra:</strong>
            {% for s in sc.sportoviste_set.all %}
                <h4>{{ s.nazev }}</h4>
                <p>{{ s.popis }}</p>
                {% endfor %}
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/web/kontakt.html
{% extends 'web/base.html' %}

{% block content %}
<div class="row-fluid">
    <div class="col-lg-12 col-md-12 col-sm-12">
        <h1>Kontakt</h1>

        
        <p>Sportovní centrum <b>Sport Centrum</b></p>
        
        <p>3. května 227, 513 01 Semily</p>
        
        <p>E-mail: <a href="mailto:info@sportcentrum.cz">info@sportcentrum.cz</a><br />
        E-mail: <a href="mailto:ekonom@sportcentrum.cz">ekonom@sportcentrum.</a><br />
        E-mail: <a href="mailto:recepce@sportcentrum.cz">recepce@sportcentrum.cz</a><br />
        Web: <a href="{{ URL }}">www.sportcentrum.cz</a><br /></p>
        
        <p>Zástupce: Vladimír Nejedlý<br />
        IČ: 71182680, DIČ: CZ71183480</p>
        
    </div>
</div>
{% endblock %}

templates/web/kredit.html
{% extends 'web/base.html' %}

{% block content %}
<div class="row-fluid">
    <div class="col-lg-12 col-md-12 col-sm-12">
        <h1>Nastavení</h1>

        {% for m in messages %}
        <div class="alert alert-info">{{ m }}</div>
        {% endfor %}
        <h3>Dobít kredit</h3>
        <form class="form-inline" role="form" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="amount_money" class="sr-only">Částka</label>
                <input type="number" class="form-control" name="amount_money" id="amount_money" placeholder="Částka">
            </div>
            <input type="hidden" name="action_type" value="money_inc">
            <button class="btn btn-default">Dobít kredit</button>
        </form>

    </div>
</div>
{% endblock %}

templates/web/nastaveni.html
{% extends 'web/base.html' %}

{% block content %}
<div class="row-fluid">
    <div class="col-lg-12 col-md-12 col-sm-12">
        <h1>Nastavení</h1>

        {% for m in messages %}
        <div class="alert alert-info">{{ m }}</div>
        {% endfor %}
        <h3>Dobít kredit</h3>
        <form class="form-inline" role="form" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="amount_money" class="sr-only">Částka</label>
                <input type="number" class="form-control" name="amount_money" id="amount_money" placeholder="Částka">
            </div>
            <input type="hidden" name="action_type" value="money_inc">
            <button class="btn btn-default">Dobít kredit</button>
        </form>

    </div>
</div>
{% endblock %}

templates/web/onas.html
{% extends 'web/base.html' %}

{% block content %}
<div class="row-fluid">
    <div class="col-lg-12 col-md-12 col-sm-12">
        <h1>O nás</h1>

	<p><b>Sportovní centrum Sport Centrum</b></p>
	
	<p>Všechny sportovní centra pohromadě.
	Jednotlivé sportovní centra skýtají možnosti sportovního využití, relaxace a zábavy, v kterém najdete luxusní ubytování hotelového typu, společenský sál, restauraci, sály pro fitness a aerobik, hernu stolního tenisu, squashový kurt, saunu, masáže, solárium a centrální halu pro tenis, volejbal, košíkovou, badminton, floorbal, trenink golfu a další sporty.
	</p>
	
    </div>
</div>
{% endblock %}

templates/web/rezervace.html
{% extends 'web/base.html' %}

{% block content %}
<div class="row-fluid">
    <div class="col-lg-12 col-md-12 col-sm-12">
        <h1>Rezervace</h1>
        {% for m in messages %}
            <p>{{ m }}</p>
        {% endfor %}
        <form class="form-inline" role="form" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="sportovni_centrum" class="sr-only">Sportovní centrum:</label>
                <select class="form-control" id="sportovni_centrum">
                    {% for sc in sport_centers %}
                        <option value="{{ sc.id }}">{{ sc }}</option>
                    {% endfor %}
                </select>

            </div>
        </form>

    <br>
    <div id="sportoviste">

    </div>
    <br>
    <div id="rezervace">

    </div>

    <div class="modal fade" id="reservation-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
        <form class="form-horizontal" method="post" action="/ajax/make_reservation/" id="reservation_form">
        {% csrf_token %}
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" id="myModalLabel">Rezervovat</h4>
          </div>
          <div class="modal-body">
              {% if user.is_authenticated %}
                    <h3 id="cena"></h3>
                    <div class="form-group">
                        <label for="rezervace_od_txt" class="col-sm-2 control-label">Od</label>
                        <div class="col-sm-10 col-md-4 col-lg-4">
                          <input type="text" class="form-control input-sm" id="rezervace_od_txt" name="rezervace_od_txt" disabled="disabled">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="rezervace_do" class="col-sm-2 control-label">Do</label>
                        <div class="col-sm-10  col-md-4 col-lg-4">
                          <select class="form-control input-sm" id="rezervace_do" name="rezervace_do">
                              <option>Test</option>
                           </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="rezervace_datum" class="col-sm-2 control-label">Datum</label>
                        <div class="col-sm-10  col-md-4 col-lg-4">
                          <input type="text" class="form-control input-sm" id="rezervace_datum_txt" name="rezervace_datum_txt" disabled="disabled">

                        </div>
                    </div>
                     {% if user.is_superuser %}
                       <div class="form-group">
                        <label for="zakaznik" class="col-sm-2 control-label">Do</label>
                        <div class="col-sm-10  col-md-4 col-lg-4">
                          <select class="form-control input-sm" id="zakaznik" name="zakaznik">
                              {% for user in users %}
                              <option value="{{ user.id }}">{{ user.get_full_name }}</option>
                              {% endfor %}
                           </select>
                        </div>

                        <div class="form-group">
                        <label for="stav" class="col-sm-2 control-label">Stav</label>
                        <div class="col-sm-10  col-md-4 col-lg-4">
                          <select class="form-control input-sm" id="stav" name="stav">
                              {% for stav_id, stav in states %}
                              <option value="{{ stav_id }}">{{ stav }}</option>
                              {% endfor %}
                           </select>
                        </div>

                     {% endif %}
                    <input type="hidden" name="rezervace_datum" id="rezervace_datum">
                    <input type="hidden" name="rezervace_od" id="rezervace_od">
                    <input type="hidden" name="sportoviste_misto" id="sportoviste_misto">
                    <input type="hidden" name="rezervace_id" id="rezervace_id" value="">
                    <input type="hidden" id="cena_interval" value="">
                    <input type="hidden" id="interval" value="">

              {% else %}
                <p>Pro provedení rezervace se musíte přihlásit</p>
              {% endif %}
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Zavřít</button>
            {% if user.is_authenticated %}
              <button type="submit" class="btn btn-primary">Potvrdit</button>
              <span id="admin_buttons">
              <a href="javascript:void(0)" onclick="pay()" class="btn btn-info">Zaplatit</a>
              <a href="javascript:void(0)" onclick="cancelReservation()" class="btn btn-danger">Zrušit rezervaci</a>
              </span>
              {% endif %}
          </div>
          </form>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

    <br>
    </div>

</div>
<div class="row-fluid">
    <div class="col-lg-4 col-md-4 col-sm-6">
        <h3>Datum</h3>
        <div id="datepicker"></div>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-6">
        <h3>Moje rezervace</h3>

        {% for r in my_reservations %}
        <p class="small">{{ r.print_user }} - <a href="{% url 'web-cancel-reservation' %}?id_rezervace={{ r.id }}">Zrušit</a></p>
        {% endfor %}

    </div>
    <div class="col-lg-4 col-md-4 col-sm-6">
        <h3>Legenda</h3>
        {% if user.is_staff %}
            <div class="legend reservation-paid">Zaplaceno</div> <br>
            <div class="clearfix"></div>
            <div class="legend reservation-reserved">Rezervováno</div> <br>
            <div class="clearfix"></div>
            <div class="legend reservation-pass">Propadlo</div> <br>
            <div class="clearfix"></div>
            <div class="legend reservation-working">Probíhá</div> <br>
        {% else %}
            <div class="legend reservation-myreservation">Má rezervace</div> <br>
            <div class="clearfix"></div>
            <div class="legend reservation-reserved">Rezervováno</div> <br>
        {% endif %}
    </div>
</div>

    <input type="hidden" name="is_admin" id="is_admin" value="{% if user.is_superuser %}1{% else %}0{% endif %}">
{% endblock %}

templates/web/vouchery.html
{% extends 'web/base.html' %}

{% block content %}
<div class="row-fluid">
    <div class="col-lg-12 col-md-12 col-sm-12">
        <h1>Mé vouchery</h1>

        {% for m in messages %}
        <div class="alert alert-info">{{ m }}</div>
        {% endfor %}
        <h3>Uplatnit voucher</h3>
        <form class="form-inline" role="form" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_voucher" class="sr-only">ID voucheru:</label>
                <input type="text" class="form-control" name="id_voucher" id="id_voucher" placeholder="ID voucheru">
            </div>
            <button class="btn btn-default">Potvrdit</button>
        </form>
        <br>
        <br>
        <h3>Uplatněné vouchery</h3>
        {% if vouchers|length > 0 %}
            <table class="table table-responsive table-striped">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Platnost od</th>
                        <th>Platnost do</th>
                        <th>Částka</th>
                    </tr>
                </thead>
                <tbody>
                    {% for voucher in vouchers %}
                    <tr>
                        <td>{{ voucher.id }}</td>
                        <td>{{ voucher.platny_od }}</td>
                        <td>{{ voucher.platny_do }}</td>
                        <td>{{ voucher.castka }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% else %}
        <p>Zatím nebyly uplatněny žádné vouchery</p>
        {% endif %}

        
    </div>
</div>
{% endblock %}